version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=flask_database
      - APP_HOST=${APP_HOST:-localhost}
      - APP_PORT=5000
      - APP_PROTOCOL=${APP_PROTOCOL:-http}
      - DEBUG=false
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flask_database
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge